# Generated by Django 3.1.7 on 2021-04-13 05:06

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayablePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('midi_file', models.FileField(upload_to='playable_midis/')),
                ('time_signature', models.IntegerField(blank=True, null=True)),
                ('time_per_note', models.FloatField(blank=True, null=True)),
                ('notes', jsonfield.fields.JSONField(blank=True, default=list, null=True)),
                ('grading', jsonfield.fields.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('notes', jsonfield.fields.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
