# Generated by Django 3.1.7 on 2021-03-29 19:31

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    replaces = [('midi', '0001_initial'), ('midi', '0002_userpiece_midi_file'), ('midi', '0003_userpiece_user'), ('midi', '0004_playablepiece'), ('midi', '0005_auto_20210329_1738'), ('midi', '0006_playable_notes'), ('midi', '0007_playablepiece_notes')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('notes', jsonfield.fields.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayablePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('midi_file', models.FileField(upload_to='playable_midis/')),
                ('notes', jsonfield.fields.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
