# Generated by Django 3.1.7 on 2021-03-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpiece',
            name='midi_file',
            field=models.FileField(default='a', upload_to='user_midis/'),
            preserve_default=False,
        ),
    ]
