# Generated by Django 3.1.7 on 2021-03-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0002_userpiece_midi_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpiece',
            name='user',
            field=models.CharField(default='Josh', max_length=40),
            preserve_default=False,
        ),
    ]
