# Generated by Django 3.1.7 on 2021-03-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0003_userpiece_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayablePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('midi_file', models.FileField(upload_to='playable_midis/')),
            ],
        ),
    ]
