# Generated by Django 3.1.7 on 2021-03-29 18:50

from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0005_auto_20210329_1738'),
    ]

    operations = [
    ]

    
    

    
