# Generated by Django 3.1.7 on 2021-03-29 19:14

from django.db import migrations
import jsonfield.fields
from backend.midi.models import PlayablePiece
from backend.midi.MidiParser import MidiParser
from backend.midi.MidiData import MidiData
from backend.midi.Util import Util
from backend.midi.MidiEventDecoder import MidiEventDecoder
import os


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0006_playable_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='playablepiece',
            name='notes',
            field=jsonfield.fields.JSONField(blank=True, default=list, null=True),
        ),
    ]

    for piece in PlayablePiece.objects.all():
        #piece.notes = {"hey":1}
        #piece.save()
        notes = []
        midi_file = os.getcwd() + "/media/" + str(piece.midi_file)
        midiData = MidiData(midi_file)
        for i in range(midiData.getNumTracks()):
            track = midiData.getTrack(i)
            for note in track.notes:
                notes.append({'time': note.startTime, 'pitch': note.pitch})
        piece.notes = notes
        piece.save()
